#api:
#    resource: "@ApiBundle/Controller/"
#    type:     annotation
#    prefix:   /api

events:
    type:     rest
    resource: "@ApiBundle/Controller/"
    prefix:   /api
    #name_prefix: api_

core_domain:
    resource: "@CoreDomainBundle/Controller/"
    type:     annotation
    prefix:   /core

app:
    resource: '@AppBundle/Controller/'
    type: annotation
