api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

core_domain:
    resource: "@CoreDomainBundle/Controller/"
    type:     annotation
    prefix:   /core

app:
    resource: '@AppBundle/Controller/'
    type: annotation
